# Generated by Django 4.0.2 on 2022-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='format: required, True=paid', verbose_name='статус платежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=1, help_text='format: required', max_length=2, verbose_name='статус заказа'),
            preserve_default=False,
        ),
    ]
