# Generated by Django 4.0.2 on 2022-02-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='cover_image',
            field=models.ImageField(upload_to='media/bicycle/', verbose_name='главная фотография велосипеда'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='images',
            field=models.ManyToManyField(to='catalog.Media', verbose_name='фотографии велосипеда'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='name',
            field=models.CharField(help_text='format: required, max_len-255', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='format: required, max_len-255', max_length=255, verbose_name='имя бренда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, help_text='format: required, decimal_places=2, max_digits=10', max_digits=10, verbose_name='полная сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='end_date',
            field=models.DateTimeField(help_text='format: YYYY-MM-DD H:M', verbose_name='Дата конца аренды'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='start_date',
            field=models.DateTimeField(help_text='format: YYYY-MM-DD H:M', verbose_name='Дата начала аренды'),
        ),
    ]
