# Generated by Django 4.0.2 on 2022-02-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='cover_image',
            field=models.ImageField(upload_to='bicycle/', verbose_name='главная фотография велосипеда'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='bicycle/'),
        ),
    ]
