# Generated by Django 4.0.2 on 2022-02-24 12:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_is_paid_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='bicycle',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='catalog_bic_content_a7957d_gin'),
        ),
    ]
