# Generated by Django 4.0.2 on 2022-02-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_create_text_search_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'В обработке'), ('DE', 'Достовляется'), ('CO', 'Завершен'), ('AC', 'Происшествие')], help_text='format: required', max_length=2, verbose_name='статус заказа'),
        ),
    ]
