# Generated by Django 4.0.2 on 2022-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='flashlight',
            field=models.BooleanField(default=False, help_text='format: required, true=needed', verbose_name='нужен ли фонарик'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='helmet',
            field=models.BooleanField(default=False, help_text='format: required, true=needed', verbose_name='нужен ли шлем'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='lock',
            field=models.BooleanField(default=False, help_text='format: required, true=needed', verbose_name='нужен ли замок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'В обработке'), ('DE', 'Достовляется'), ('CO', 'Завершен'), ('AC', 'Происшествие')], default='PR', help_text='format: required', max_length=2, verbose_name='статус заказа'),
        ),
    ]
