# Generated by Django 4.0.2 on 2022-03-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=1, help_text='format: required', verbose_name='количество'),
        ),
    ]
